# Creates directory structure for first time and installs all the packages needed for the project
proj_packages <- c("tidyverse", "data.table", "ncdf4", "raster", "leaflet",
                   "rvest", "shiny")

if (length(setdiff(proj_packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(proj_packages, rownames(installed.packages())))  
}

dir.create('./results')
dir.create('./results/database')
dir.create('./data')
dir.create('./data/geodata')
dir.create('./data/input')
dir.create('./data/input/gridded')
dir.create('./data/input/gridded/cru_ts4.01')
dir.create('./data/input/gridded/luterbacher')
dir.create('./data/input/gridded/luterbacher/raw')
dir.create('./data/input/gridded/owda')
dir.create('./data/input/gridded/pauling')
dir.create('./data/input/point')
dir.create('./data/input/point/ghcn')
dir.create('./data/input/point/ghcn/raw')
dir.create('./data/input/point/ghcn/raw/precip_d')
dir.create('./data/input/point/ghcn/raw/precip_m')
dir.create('./data/input/point/ghcn/raw')
dir.create('./data/input/point/ljungqvist_p/raw')
dir.create('./data/input/point/ljungqvist_t/raw')
dir.create('./data/input/point/pages2k')
dir.create('./data/input/used_in_models')
dir.create('./data/input/used_in_models/mhm')
dir.create('./data/other')
dir.create('./data/other/grdb')
dir.create('./data/other/grdb/raw')
dir.create('./data/output')
dir.create('./data/output/database')